### ISSUE TITLE
Will there be a 44.1 or 48kHz pre-trained model released?

### ISSUE THREAD

**Issue by youssefavx** [haoxiangsnr/FullSubNet#16]
Hi guys! Your work is absolutely amazing and inspiring. Trying your model on data that was not on your datasets, it performed very well. 

I did have to convert to 16kHz first since as I understand, it was trained on 16kHz? 

My question is: will you guys release a 44.1kHz or 48kHz pre-trained model in the near future or not? 

While I could try my hand at training that model, I'm nowhere near experienced as you guys at this and feel that I'd miss so many things and would not be able to create a model that generalizes as well as you have, or maybe you can prove me wrong.

**Comment by youssefavx** [comment]
Hi @haoxiangsnr I am now curious to train this on 44.1kHz data. I just want to ask:

1. Is this the only thing I have to change to train in 44.1Khz: `sr = 16000` -> `sr = 44100` in  https://github.com/haoxiangsnr/FullSubNet/blob/main/recipes/dns_interspeech_2020/fullsubnet/train.toml or do I have to change more things to make it work on that data? 
2. I want to train a model to your same level of quality which I found very impressive, how many epochs do I need to train for? 
3. What datasets did you use to train your model, and are there 44.1kHz versions of them?
4. Is it possible to train this model I want to train on Google Colab or do I need more compute? I have access to Google's TPU Research Cloud and have 30 days free which I might try if I really need to. 
5. If I also train the model on input that is low-passed (so you can't hear the high frequencies), will it be able to 'dream' or 'infer' high frequency features of a voice if I also give it an output that is high frequency?

**Comment by youssefavx** [comment]
Okay I just tried to run a very small test on Colab. I downloaded the "Fullband" folder from DNS, and I assumed that in this file:

```
clean_dataset = "/apdcephfs/share_976139/xianghao/Datasets_share_976139/DNS-INTERSPEECH-2020/datasets/clean_0.6.txt"
```
There's supposed to be something that looks like this:

```
/content/FullSubNet/dns_interspeech_2020/datasets_fullband/clean_fullband/russian_speech/M-AILABS_Speech_Dataset/ru_RU_47hrs_48k/female/hajdurova/strashnaya_minuta/wavs/strashnaya_minuta_s000764.wav
/content/FullSubNet/dns_interspeech_2020/datasets_fullband/clean_fullband/russian_speech/M-AILABS_Speech_Dataset/ru_RU_47hrs_48k/female/hajdurova/strashnaya_minuta/wavs/strashnaya_minuta_s000765.wav
/content/FullSubNet/dns_interspeech_2020/datasets_fullband/clean_fullband/russian_speech/M-AILABS_Speech_Dataset/ru_RU_47hrs_48k/female/hajdurova/strashnaya_minuta/wavs/strashnaya_minuta_s000766.wav
...
```
And so on... 

So this is what I did for the clean.txt file, as well as the noise.txt file where I simply used the noise folder called `noise_fullband` in the fullband dataset. 

I also downloaded `MIRD Database (RT60 = 160 ms, spacing 3-3-3-8-3-3-3)` found here: http://www.ind.rwth-aachen.de/en/research/tools-downloads/multichannel-impulse-response-database/

And I unzipped it and I did the same thing for the `rir.txt` file: 

```
/content/FullSubNet/recipes/dns_interspeech_2020/Impulse_response_Acoustic_Lab_Bar-Ilan_University__Reverberation_0.160s__3-3-3-8-3-3-3/Impulse_response_Acoustic_Lab_Bar-Ilan_University_(Reverberation_0.160s)_3-3-3-8-3-3-3_2m_015.mat
/content/FullSubNet/recipes/dns_interspeech_2020/Impulse_response_Acoustic_Lab_Bar-Ilan_University__Reverberation_0.160s__3-3-3-8-3-3-3/Impulse_response_Acoustic_Lab_Bar-Ilan_University_(Reverberation_0.160s)_3-3-3-8-3-3-3_1m_330.mat
...
```

I then tried running this command: 

```
!CUDA_VISIABLE_DEVICES=0 python train.py -C fullsubnet/train.toml -N 1
```

And I got this error: 

```
RuntimeError: Error opening '/content/FullSubNet/recipes/dns_interspeech_2020/datasets_fullband/clean_fullband/french_data/M-AILABS_Speech_Dataset/fr_FR_190hrs_16k/female/nadine_eckert_boulet/la_vampire/wavs/la_vampire_19_f000239.wav': File contains data in an unknown format.
```

<details><summary>Full stack trace:</summary>
```
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
1/1 process initialized.
/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
The configurations are as follows: 
{
    'meta': {
        'save_dir': 
'/apdcephfs/share_976139/xianghao/Experiments_share_976139/FullSubNet',
        'description': 'This is a description of FullSubNet experiment.',
        'seed': 0,
        'use_amp': True,
        'cudnn_enable': True,
        'experiment_name': 'train',
        'config_path': 'fullsubnet/train.toml',
        'preloaded_model_path': None
    },
    'acoustics': {
        'n_fft': 512,
        'win_length': 512,
        'sr': 16000,
        'hop_length': 256
    },
    'loss_function': {'name': 'mse_loss', 'args': {}},
    'optimizer': {'lr': 0.001, 'beta1': 0.9, 'beta2': 0.999},
    'train_dataset': {
        'path': 'dataset_train.Dataset',
        'args': {
            'clean_dataset': 
'/content/FullSubNet/recipes/dns_interspeech_2020/clean.txt',
            'clean_dataset_limit': False,
            'clean_dataset_offset': 0,
            'noise_dataset': 
'/content/FullSubNet/recipes/dns_interspeech_2020/noise.txt',
            'noise_dataset_limit': False,
            'noise_dataset_offset': 0,
            'num_workers': 36,
            'pre_load_clean_dataset': False,
            'pre_load_noise': False,
            'pre_load_rir': False,
            'reverb_proportion': 0.75,
            'rir_dataset': 
'/content/FullSubNet/recipes/dns_interspeech_2020/rir.txt',
            'rir_dataset_limit': False,
            'rir_dataset_offset': 0,
            'silence_length': 0.2,
            'snr_range': [-5, 20],
            'sr': 16000,
            'sub_sample_length': 3.072,
            'target_dB_FS': -25,
            'target_dB_FS_floating_value': 10
        },
        'dataloader': {
            'batch_size': 38,
            'num_workers': 12,
            'drop_last': True,
            'pin_memory': True
        }
    },
    'validation_dataset': {
        'path': 'dataset_validation.Dataset',
        'args': {
            'dataset_dir_list': [
                '/apdcephfs/share_976139/xianghao/Datasets_share_976139/DNS-INTE
RSPEECH-2020/datasets/test_set/synthetic/with_reverb/',
                '/apdcephfs/share_976139/xianghao/Datasets_share_976139/DNS-INTE
RSPEECH-2020/datasets/test_set/synthetic/no_reverb/'
            ],
            'sr': 16000
        }
    },
    'model': {
        'path': 'model.Model',
        'args': {
            'sb_num_neighbors': 15,
            'fb_num_neighbors': 0,
            'num_freqs': 257,
            'look_ahead': 2,
            'sequence_model': 'LSTM',
            'fb_output_activate_function': 'ReLU',
            'sb_output_activate_function': False,
            'fb_model_hidden_size': 512,
            'sb_model_hidden_size': 384,
            'weight_init': False,
            'norm_type': 'offline_laplace_norm',
            'num_groups_in_drop_band': 2
        }
    },
    'trainer': {
        'path': 'trainer.Trainer',
        'train': {
            'clip_grad_norm_value': 10,
            'epochs': 9999,
            'save_checkpoint_interval': 1
        },
        'validation': {
            'save_max_metric_score': True,
            'validation_interval': 1
        },
        'visualization': {
            'metrics': ['WB_PESQ', 'NB_PESQ', 'STOI', 'SI_SDR'],
            'n_samples': 10,
            'num_workers': 12
        }
    }
}
This project contains 1 models, the number of the parameters is: 
        Network 1: 5.637635 million.
The amount of parameters in the project is 5.637635 million.
=============== 1 epoch ===============
[0 seconds] Begin training...
Training:   0% 0/12086 [00:00<?, ?it/s]/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py:481: UserWarning: This DataLoader will create 12 worker processes in total. Our suggested max number of worker in current system is 2, which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  cpuset_checked))
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
Warning: please export TSAN_OPTIONS='ignore_noninstrumented_modules=1' to avoid false positive reports from the OpenMP runtime!
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
/usr/local/lib/python3.7/site-packages/librosa/core/audio.py:165: UserWarning: PySoundFile failed. Trying audioread instead.
  warnings.warn("PySoundFile failed. Trying audioread instead.")
Training:   0% 0/12086 [00:29<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 116, in <module>
    join=True)
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 150, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/content/FullSubNet/recipes/dns_interspeech_2020/train.py", line 74, in entry
    trainer.train()
  File "/content/FullSubNet/audio_zen/trainer/base_trainer.py", line 318, in train
    self._train_epoch(epoch)
  File "/content/FullSubNet/recipes/dns_interspeech_2020/fullsubnet/trainer.py", line 27, in _train_epoch
    for noisy, clean in self.train_dataloader:
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/usr/local/lib/python3.7/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
audioread.exceptions.NoBackendError: Caught NoBackendError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/librosa/core/audio.py", line 149, in load
    with sf.SoundFile(path) as sf_desc:
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 629, in __init__
    self._file = self._open(file, mode_int, closefd)
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 1184, in _open
    "Error opening {0!r}: ".format(self.name))
  File "/usr/local/lib/python3.7/site-packages/soundfile.py", line 1357, in _error_check
    raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
RuntimeError: Error opening '/content/FullSubNet/recipes/dns_interspeech_2020/datasets_fullband/clean_fullband/french_data/M-AILABS_Speech_Dataset/fr_FR_190hrs_16k/female/nadine_eckert_boulet/la_vampire/wavs/la_vampire_19_f000239.wav': File contains data in an unknown format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/content/FullSubNet/recipes/dns_interspeech_2020/dataset_train.py", line 187, in __getitem__
    clean_y = load_wav(clean_file, sr=self.sr)
  File "/content/FullSubNet/audio_zen/acoustics/feature.py", line 117, in load_wav
    return librosa.load(os.path.abspath(os.path.expanduser(file)), mono=False, sr=sr)[0]
  File "/usr/local/lib/python3.7/site-packages/librosa/core/audio.py", line 166, in load
    y, sr_native = __audioread_load(path, offset, duration, dtype)
  File "/usr/local/lib/python3.7/site-packages/librosa/core/audio.py", line 190, in __audioread_load
    with audioread.audio_open(path) as input_file:
  File "/usr/local/lib/python3.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
```
</details>

Does it not support wav files?

**Comment by youssefavx** [comment]
I just tried deleting that file, re-writing `clean.txt` and running again and I get the same error:
```
RuntimeError: Error opening '/content/FullSubNet/recipes/dns_interspeech_2020/datasets_fullband/clean_fullband/french_data/M-AILABS_Speech_Dataset/fr_FR_190hrs_16k/male/zeckou/l_ile_mysterieuse/wavs/l_ile_mysterieuse_3_15_f000090.wav': File contains data in an unknown format.
```

**Comment by youssefavx** [comment]
Okay, I assume this has to do with some kind of file conversion problem, at the end of the error it says:

```
audioread.exceptions.NoBackendError
```

After some googling it seems that one problem that might be responsible for this is lack of ffmpeg. When I run `!ffmpeg` in Colab, it seems it's installed:
```
ffmpeg version 9c33b2f Copyright (c) 2000-2021 the FFmpeg developers
  built with gcc 9.3.0 (crosstool-NG 1.24.0.133_b0863d8_dirty)
  configuration: --prefix=/home/conda/feedstock_root/build_artifacts/ffmpeg_1627813612080/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac --cc=/home/conda/feedstock_root/build_artifacts/ffmpeg_1627813612080/_build_env/bin/x86_64-conda-linux-gnu-cc --disable-doc --disable-openssl --enable-avresample --enable-gnutls --enable-gpl --enable-hardcoded-tables --enable-libfreetype --enable-libopenh264 --enable-libx264 --enable-pic --enable-pthreads --enable-shared --enable-static --enable-version3 --enable-zlib --enable-libmp3lame --pkg-config=/home/conda/feedstock_root/build_artifacts/ffmpeg_1627813612080/_build_env/bin/pkg-config
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'
```
I also pip installed it and same error occurs again.

**Comment by youssefavx** [comment]
It seems the difficulty its having opening up files using pysoundfile has something to do with the colab imported version: https://github.com/bastibe/python-soundfile/issues/203

**Comment by youssefavx** [comment]
Indeed when I do:
```
soundfile.__version__
```
I get:
```
'0.10.3'
```

The confusing thing is this is after I did:

```
!conda update pysoundfile
```
And
```
!pip install -U pysoundfile
```

**Comment by youssefavx** [comment]
![fixing_problems](https://user-images.githubusercontent.com/56129524/131237100-0b651d63-e802-4411-aaac-678481c689be.png)
