### ISSUE TITLE
error !

### ISSUE THREAD

**Issue by vinh1988** [haoxiangsnr/FullSubNet#25]
hi @haoxiangsnr,
I run pre-training on Google Colab followed by this link:
https://github.com/haoxiangsnr/FullSubNet/blob/main/docs/getting_started.md
but I got an issue like this:
command: !python inference.py -C /content/FullSubNet/recipes/dns_interspeech_2020/fullband_baseline/inference.toml -M /content/drive/MyDrive/Colab_Notebooks/FullSubNet/fullsubnet_best_model_58epochs.tar -O /content/drive/MyDrive/Colab_Notebooks/FullSubNet/output_dir
result: 
----------------------------------------------------
Loading inference dataset...
Loading model...
Traceback (most recent call last):
  File "inference.py", line 32, in <module>
    main(configuration, checkpoint_path, output_dir)
  File "inference.py", line 16, in main
    output_dir
  File "/content/FullSubNet/recipes/dns_interspeech_2020/inferencer.py", line 50, in __init__
    super().__init__(config, checkpoint_path, output_dir)
  File "/content/FullSubNet/audio_zen/inferencer/base_inferencer.py", line 27, in __init__
    self.model, epoch = self._load_model(config["model"], checkpoint_path, self.device)
  File "/content/FullSubNet/audio_zen/inferencer/base_inferencer.py", line 91, in _load_model
    model = initialize_module(model_config["path"], args=model_config["args"], initialize=True)
  File "/content/FullSubNet/audio_zen/utils.py", line 87, in initialize_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'model'
------------------------------------------------------
please help me a hand, thanks a lot

**Comment by l2009312042** [comment]
modify  the file  inference.toml ，it will be ok 
[model]
path = "fullsubnet.model.Model"

**Comment by haoxiangsnr** [comment]
Fixed it in the new version.  Now, you could use both "fullsubnet.model.Model" and "model.Model". 

The project will automatically search the nearest "model.py" file.
